List<String> sarlavha = [
  "Simsiz printerni Windows 10 ga qanday ulash mumkin",
  "Simli printerni Windows 10 ga qanday ulash mumkin",
  "Umumiy printer resurslari",
  "Dasturiy ta'minot yoki drayverlarni yuklab olishim kerakmi?",
];
List<String> matn = [
  "Printerni Wi-Fi tarmog'iga ulanish uchun sozlash printerni tarmoq ichidagi istalgan joydan simsiz foydalanish imkonini beradi. Quyidagi amallarni bajaring:\n\n1. Printeringiz yoqilgan va Wi-Fi tarmog'ingizga ulanganligiga ishonch hosil qiling.\n\nAytgancha:  Printeringizni Wi-Fi tarmog'ingizga ulash uchun ishlab chiqaruvchining ko'rsatmalariga amal qiling. Printeringiz Windows 10 kompyuteringiz bilan bir xil tarmoqqa ulangan bo'lishi kerak.\n2. Windows 10 kompyuteringizda ekranning pastki chap burchagidan Boshlash menyusini (Windows logotipi belgisi) oching.\n\n3. Boshlash menyusining chap tomonidagi Sozlamalar (kichik tishli belgi) ni tanlang .\n 4. Windows sozlamalari oynasida Qurilmalar opsiyasini tanlang .\n\n5. Oynaning chap tomonida Printers & Scanners opsiyasini tanlang.\n\n6. Oynaning o'ng tomonida yangi printer qo'shish uchun (+) tugmasini bosing.\n\n7. Windows 10 endi tarmog'ingizdagi barcha printerlar va skanerlarni qidiradi va keyin ularni ro'yxatda ko'rsatadi. Printeringiz model raqami bo‘yicha ko‘rsatilgandan so‘ng uni tanlang va “Qurilmani qo‘shish” tugmasini bosing .\n8. Windows endi printeringizga ulanishni o'rnatadi va uning ishlashi uchun barcha kerakli drayverlarni o'rnatadi. Tugallangach, printer tayyor deb aytadi .",
  "Agar printeringiz simsiz ulanishni taklif qilmasa yoki siz shunchaki simli USB ulanishidan foydalanmoqchi bo'lsangiz, uni Windows 10 kompyuteringizga ulang. Simsiz printerdan farqli o'laroq, Windowsning oldingi versiyalaridan farqli o'laroq, hech qanday sozlash kerak emas. USB printerni ulaganingizdan so'ng, u avtomatik ravishda Windows tizimida o'rnatiladi.",
  "Muayyan printeringiz haqida qo'shimcha ma'lumot olish uchun qurilmangiz ishlab chiqaruvchisi bilan maslahatlashing. Printer ishlab chiqaruvchisi saytida qurilmangizga yordam beradigan qoʻllanmalar, qoʻllanma drayverlari va qoʻshimcha dasturlar boʻlishi mumkin. Qulaylik uchun biz quyida eng keng tarqalgan printerlarni qo'llab-quvvatlash havolalarini taqdim etdik.\n   https://www.usa.canon.com/support   \n   https://support.hp.com/us-en?openCLC=true   \n   https://www.brother-usa.com/brother-support   \n   https://epson.com/Support/sl/s   \n   https://www.support.xerox.com/   \n   http://support.lexmark.com/index?page=productSelection&channel=supportAndDownloads&locale=en&userlocale=EN_US   ",
  "Ba'zi ishlab chiqaruvchilar printeringiz bilan ishlatish uchun yuklab olinadigan qo'shimcha dasturiy ta'minotni taklif qilishsa-da, odatda hamma narsani ishga tushirish uchun qo'shimcha dastur kerak emas. Bundan tashqari, drayverlar qo'lda yuklab olingan bo'lsa, Windows 10 ishga tushirish uchun kerak bo'lgan hamma narsani avtomatik ravishda yuklab oladi.",
];